rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: self-hd-production
    metrics_path: /metrics
    static_configs:
      - targets:
          - production:3000

